[build]
  command = "npm run build -- --configuration production"
  publish = "dist/frontend/browser"
  ignore = "git diff --quiet HEAD~ HEAD -- frontend/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
